xception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001ABC725EC10>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 351, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):        
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001ABC725EC10>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 351, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001ABC7298550>
Traceback (most recent call last):
  File "c:\program files\python39\lib\tkinter\__init__.py", line 4016, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread